(function(){
document.querySelectorAll("[data-support-open]").forEach(element=>{element.removeAttribute("data-support-open");element.href="https://t.me/AYAT808820";element.target="_blank";element.rel="noopener noreferrer"});
})();
(function(){
const session=JSON.parse(localStorage.getItem("vanguardprimeSession")||"null");if(!session?.email){fetch("/api/me",{credentials:"same-origin"}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();localStorage.setItem("vanguardprimeSession",JSON.stringify({email:data.user.email,name:data.user.name,signedInAt:new Date().toISOString(),serverAuthenticated:true}));location.reload()}).catch(()=>location.replace("login.html?next=dashboard.html"));return}
const name=(session.name||session.email.split("@")[0]).replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),body=document.body,toast=document.querySelector(".toast");
document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];const welcomeActions=document.querySelector(".welcome-actions");if(welcomeActions)welcomeActions.innerHTML='<a class="button button-gold" href="investments.html">Invest Now</a><a class="button button-ghost" href="dashboard.html">Sign Up / Login</a><a class="button button-ghost" href="investments.html">Explore Other Opportunities</a>';
document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=async()=>{try{await fetch("/api/logout",{method:"POST",credentials:"same-origin"})}finally{localStorage.removeItem("vanguardprimeSession");localStorage.removeItem("vanguardprimeProfile");location.replace("login.html")}};
const money=c=>Number(c||0).toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2}),safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),date=v=>new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}),dateTime=v=>new Date(v).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"});
const dashboardPackages=document.createElement("section");dashboardPackages.className="dashboard-packages";dashboardPackages.innerHTML='<div class="dashboard-package-heading"><div><span class="eyebrow">AVAILABLE OPPORTUNITIES</span><h2>Investment opportunities</h2></div><a href="investments.html">View all →</a></div><div class="dashboard-package-grid" data-dashboard-package-grid><div class="empty-dynamic">Loading opportunities…</div></div>';document.querySelector(".dashboard-grid").before(dashboardPackages);
fetch("/api/investment-plans").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Opportunities could not be loaded.");return data.plans||[]}).then(plans=>{const grid=dashboardPackages.querySelector("[data-dashboard-package-grid]");grid.innerHTML=plans.length?plans.map(plan=>{const duration=Number(plan.duration_days)===365?"1 year":`${Number(plan.duration_days)} days`,minimum=money(Number(plan.minimum_cents)/100),maximum=plan.maximum_cents?money(Number(plan.maximum_cents)/100):"Unlimited";return `<article class="card dashboard-package-card"><div><span>${safe(plan.category)}</span><strong>${safe(plan.name)}</strong></div><b>${duration}</b><dl><div><dt>Investment range</dt><dd>${minimum} – ${maximum}</dd></div><div><dt>Risk level</dt><dd>${safe(plan.risk_level||"Review required")}</dd></div><div><dt>Fees &amp; terms</dt><dd>View details</dd></div></dl><a href="investments.html?view=buy&plan=${encodeURIComponent(plan.public_id)}">Review opportunity →</a></article>`}).join(""):'<div class="empty-dynamic">No investment opportunities are available.</div>'}).catch(()=>dashboardPackages.remove());
fetch("/api/dashboard",{credentials:"same-origin"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Dashboard data could not be loaded.");return d}).then(d=>{
const runningCount=Number(d.portfolio.runningInvestmentCount||0),activePlan=d.investmentOrders.find(order=>["active","running"].includes(String(order.status).toLowerCase()));const metrics={balance:money(Number(d.wallet.available_cents)/100),deposits:money(Number(d.totals.total_deposits)/100),bonus:money(Number(d.totals.bonus_cents)/100),pending:money(Number(d.totals.pending_withdrawals)/100),running:`${runningCount} active plan${runningCount===1?"":"s"}`};Object.entries(metrics).forEach(([key,value])=>{const element=document.querySelector(`[data-metric="${key}"]`);if(element)element.textContent=value});document.querySelector('[data-overview="username"]').textContent=d.user.name||name;document.querySelector('[data-overview="registered"]').textContent=date(d.user.createdAt);document.querySelector('[data-overview="last-access"]').textContent=dateTime(d.lastAccess||new Date());document.querySelector('[data-overview="plan"]').textContent=activePlan?.plan_name||"No active plan";
const labels={not_submitted:"Not submitted",pending:"Pending review",approved:"Verified",rejected:"Not approved",resubmission_required:"Resubmission required"},kycLabel=labels[d.user.kycStatus]||labels.not_submitted,badge=document.querySelector("[data-kyc-mini]"),warning=document.querySelector("[data-kyc-warning]"),kycStatus=document.querySelector("[data-kyc-verification]"),emailStatus=document.querySelector("[data-email-verification]");if(emailStatus)emailStatus.textContent=d.user.emailVerified?"Verified":"Confirmation required";if(kycStatus)kycStatus.textContent=kycLabel;if(badge){badge.textContent=`KYC ${kycLabel}`;badge.classList.toggle("submitted",d.user.kycStatus==="approved")}if(d.user.kycStatus==="approved")warning?.remove();else if(warning&&d.user.kycStatus!=="not_submitted"){warning.querySelector("strong").textContent=d.user.kycStatus==="pending"?"Your KYC is awaiting review":"Your KYC needs attention";warning.querySelector("span").textContent=d.user.kycReviewNote||"Open your KYC page to review the current status.";warning.querySelector("a").textContent="View KYC →"}
const investments=document.querySelector("[data-investments]");if(d.investmentOrders.length)investments.innerHTML=d.investmentOrders.slice(0,5).map(x=>`<div class="activity-row"><div><strong>${safe(x.plan_name)}</strong><span>${Number(x.durationDays||x.term_days||x.duration_days)} day term · ${safe(x.status)}</span></div><div><strong>${money(Number(x.currentValueCents)/100)}</strong><span class="gold">${money(Number(x.profitCents)/100)} profit</span></div></div>`).join("");
const tx=document.querySelector("[data-transactions]");if(d.transactions.length)tx.innerHTML=d.transactions.slice(0,5).map(x=>`<div class="activity-row"><div><strong>${safe(x.type.replace(/\b\w/g,c=>c.toUpperCase()))}</strong><span>${safe(x.method||"Wallet")} · ${date(x.created_at)}</span></div><div><strong>${x.direction==="credit"?"+":"−"}${money(Number(x.amount_cents)/100)}</strong><span>${safe(x.status)}</span></div></div>`).join("");
}).catch(e=>{toast.textContent=e.message;toast.classList.add("show")});
})();
