(function(){
const session=JSON.parse(localStorage.getItem("vanguardprimeSession")||"null");if(!session?.email){location.replace("login.html?next=investments.html");return}
const name=(session.name||session.email.split("@")[0]).replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),body=document.body,content=document.querySelector("#investment-content"),title=document.querySelector("[data-page-title]"),toast=document.querySelector(".toast");let plans=[],wallet=0;
document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];
const kyc=JSON.parse(localStorage.getItem("kycSubmission")||"null"),kycVerified=String(kyc?.status||"").toLowerCase()==="verified",kycBadge=document.querySelector("[data-kyc-mini]");if(kycBadge&&kyc){kycBadge.textContent=`KYC ${kyc.status}`;kycBadge.classList.toggle("submitted",kycVerified)}
const money=n=>Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}),safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),message=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove("show"),2600)};
const normalize=p=>({id:p.public_id,name:p.name,category:p.category,min:p.minimum_cents/100,max:p.maximum_cents/100,nav:p.nav_cents/100,daily:p.daily_return_bps/100,total:p.projected_return_bps/100,days:p.duration_days,fee:p.management_fee_bps/100,risk:p.risk_level,description:p.description||""});
async function load(){const [pr,wr]=await Promise.all([fetch("/api/investment-plans"),fetch("/api/wallet",{credentials:"same-origin"})]),pd=await pr.json(),wd=await wr.json();if(!pr.ok)throw new Error(pd.error);if(!wr.ok)throw new Error(wd.error);plans=pd.plans.map(normalize);wallet=Number(wd.wallet.availableCents)/100}
function planCard(p){const outcome=p.min*(1+p.total/100);return `<article class="card plan-card"><div class="plan-heading"><div><span>${safe(p.category)} OPPORTUNITY</span><h3>${safe(p.name)}</h3></div><b>${p.days===365?"1 year":`${p.days} days`}</b></div><div class="return-highlight"><span>Proposed outcome</span><strong>${money(outcome)}</strong></div><p class="plan-description">${safe(p.description)}</p><div class="plan-facts"><div><span>Investment amount</span><strong>${money(p.min)}</strong></div><div><span>Approximate ETB</span><strong>${Math.round(p.min*160).toLocaleString()} ETB</strong></div><div><span>Term</span><strong>${p.days===365?"1 year":`${p.days} days`}</strong></div><div><span>Company risk category</span><strong>${safe(p.risk)}</strong></div><div><span>Management fee</span><strong>${p.fee}%</strong></div></div><small>Proposed outcome is not guaranteed. Review eligibility and approved terms.</small><button class="invest-btn" data-buy="${safe(p.id)}">Review opportunity</button></article>`}
function packageSections(){const grouped=new Map();for(const plan of plans){if(!grouped.has(plan.category))grouped.set(plan.category,[]);grouped.get(plan.category).push(plan)}return [...grouped].map(([type,items])=>`<section class="package-type-section"><div class="package-type-heading"><div><span class="eyebrow">INVESTMENT TYPE</span><h2>${safe(type)} Packages</h2></div><span>${items.length} package${items.length===1?"":"s"}</span></div><div class="plan-grid">${items.map(planCard).join("")}</div></section>`).join("")}
function list(){const minimum=plans.length?Math.min(...plans.map(plan=>plan.min)):0;title.textContent="Opportunities";content.className="main invest-main";content.innerHTML=`<section class="welcome"><div><span class="eyebrow">AYAT SHARES</span><h1>Your Path to Succeed</h1><p>Review Regular and VIP opportunities with clear amounts and terms.</p></div><div class="wallet-summary"><span>Available balance</span><strong>${money(wallet)}</strong><a href="wallet.html?view=deposit">Deposit funds →</a></div></section>${kycVerified?"":`<section class="kyc-warning"><div><strong>${kyc?"KYC review is pending":"KYC verification has not been completed"}</strong><span>Complete identity verification before an opportunity can be approved.</span></div><a href="kyc.html">${kyc?"View status":"Verify now"} →</a></section>`}<section class="investment-explainer"><strong>${plans.length?`Minimum entry: ${money(minimum)}`:"No active opportunities"}</strong></section>${plans.length?packageSections():'<section class="card empty-dynamic">No opportunities are currently available.</section>'}<section class="business-preview"><article style="background-image:url('images/ayat kazanchis apartments.webp')"><b>Real estate</b></article><article style="background-image:url('images/gold-oil-gas.png');background-position:left"><b>Mining & gold</b></article><article style="background-image:url('images/gold-oil-gas.png');background-position:right"><b>Oil & gas</b></article><article style="background-image:url('images/import-export.png')"><b>Import & export</b></article></section><section class="card btc-wallet"><div><span class="eyebrow">THREE APPROVED METHODS</span><h2>USDT, bank transfer or Bitcoin</h2><p>Choose the payment route that works for you.</p></div><a class="button button-gold" href="wallet.html?view=deposit">Make a deposit</a></section>`;content.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>goBuy(b.dataset.buy))}
function goBuy(id){history.pushState({},"",`investments.html?view=buy&plan=${encodeURIComponent(id)}`);buy(id)}
function buy(id){const p=plans.find(x=>x.id===id);if(!p){history.replaceState({},"","investments.html");return list()}title.textContent=p.name;content.className="main flow-main";content.innerHTML=`<section class="hero"><div><span class="eyebrow">${safe(p.category)} OPPORTUNITY</span><h1>${safe(p.name)}</h1><p>${p.days===365?"1 year":`${p.days} days`} term · proposed outcome subject to approved terms</p></div><div class="balance"><small>Available Balance</small><div class="balance-value">${money(wallet)}</div></div></section><form class="card form-card invest-form"><label class="field-label" for="amount">Investment Amount</label><div class="money-input"><span>$</span><input id="amount" name="amount" type="number" min="${p.min}" max="${p.max}" step=".01" value="${p.min}" inputmode="decimal"></div><p class="helper">Choose between ${money(p.min)} and ${money(p.max)}.</p><div class="investment-summary"><div><span>Term</span><strong>${p.days===365?"1 year":`${p.days} days`}</strong></div><div><span>Proposed outcome</span><strong data-outcome>${money(p.min*(1+p.total/100))}</strong></div><div><span>Risk category</span><strong>${safe(p.risk)}</strong></div><div><span>Management fee</span><strong>${p.fee}%</strong></div></div><p class="helper">All Investments are backed by real bussiness assets</p><div class="funding-state" data-state></div><button class="submit-btn" type="submit">Continue</button><a class="back-link" href="investments.html">← Back to opportunities</a></form>`;
const form=content.querySelector("form"),input=form.amount,state=form.querySelector("[data-state]"),button=form.querySelector("button");function update(){const amount=Number(input.value)||0,valid=amount>=p.min&&amount<=p.max,short=Math.max(0,amount-wallet);form.querySelector("[data-outcome]").textContent=money(amount*(1+p.total/100));state.className=`funding-state ${short?"needs-funds":"ready"}`;state.innerHTML=!valid?`Enter an amount within this opportunity's limits.`:short?`<strong>${money(short)} more is needed.</strong><span>Continue to choose USDT, bank transfer or Bitcoin.</span>`:`<strong>Your balance covers this investment.</strong><span>Continue to review and confirm.</span>`;button.disabled=!valid;button.textContent=short?"Deposit & Continue":"Review Investment"}input.oninput=update;update();
form.onsubmit=async e=>{e.preventDefault();const amount=Number(input.value),short=Math.max(0,amount-wallet);if(short){sessionStorage.setItem("investmentReturn",JSON.stringify({plan:p.id,amount}));location.href=`wallet.html?view=deposit&amount=${encodeURIComponent(short.toFixed(2))}&return=investment`;return}if(!confirm(`Submit ${p.name} with ${money(amount)} for review?`))return;button.disabled=true;button.textContent="Submitting…";try{const r=await fetch("/api/investment-orders",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({planId:p.id,amount})}),d=await r.json();if(!r.ok){if(d.code==="INSUFFICIENT_BALANCE"){location.href=`wallet.html?view=deposit&amount=${(d.shortfallCents/100).toFixed(2)}&return=investment`;return}throw new Error(d.error)}message(d.message);setTimeout(()=>location.href="dashboard.html",700)}catch(err){message(err.message);button.disabled=false;update()}}}
async function render(){try{if(!plans.length)await load();const q=new URLSearchParams(location.search);q.get("view")==="buy"?buy(q.get("plan")):list()}catch(e){content.className="main";content.innerHTML=`<section class="card empty-dynamic">${safe(e.message||"Investment plans could not be loaded.")}</section>`}}
document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("vanguardprimeSession");location.replace("login.html")};addEventListener("popstate",render);render();
})();
