(function(){
const form=document.querySelector('form[action="#"]');if(!form)return;
const style=document.createElement("style");style.textContent=".auth-alert{margin-bottom:14px;padding:11px 12px;border-radius:6px;font-size:12px}.auth-alert.error{border:1px solid #c39a4566;background:#fff8e8;color:#654c18}.field-error{margin-top:5px;color:#b3132c;font-size:10px}.input-error{border-color:#b3132c!important}";document.head.appendChild(style);
const referral=form.elements.referral_code,feedback=form.querySelector("[data-referral-feedback]"),code=form.login_code,confirmation=form.login_code_confirmation;let timer,validatedCode="";
function clearErrors(){form.querySelectorAll(".auth-alert,.field-error").forEach(x=>x.remove());form.querySelectorAll(".input-error").forEach(x=>x.classList.remove("input-error"))}
function alertMessage(text){const element=document.createElement("div");element.className="auth-alert error";element.textContent=text;form.prepend(element)}
function fieldErrors(fields={}){Object.entries(fields).forEach(([name,text])=>{const map={firstName:"first_name",lastName:"last_name",referralCode:"referral_code"},input=form.elements[map[name]||name];if(!input)return;input.classList.add("input-error");const error=document.createElement("div");error.className="field-error";error.textContent=text;input.closest("div").appendChild(error)})}
async function validateReferral(){const value=referral.value.trim().toUpperCase();referral.value=value;validatedCode="";if(!value){feedback.textContent="";return true}feedback.textContent="Checking referral code…";try{const response=await fetch(`/api/referrals/validate?code=${encodeURIComponent(value)}`),data=await response.json();if(!response.ok)throw new Error(data.error||"Invalid referral code.");validatedCode=value;feedback.textContent="Referral code applied successfully.";feedback.style.color="#287451";return true}catch(error){feedback.textContent=error.message;feedback.style.color="#b3132c";return false}}
referral.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(validateReferral,350)});referral.addEventListener("blur",validateReferral);const linked=new URLSearchParams(location.search).get("ref");if(linked){referral.value=linked.toUpperCase();validateReferral()}
form.onsubmit=async event=>{event.preventDefault();clearErrors();if(!form.checkValidity()){form.reportValidity();return}if(referral.value.trim()&&validatedCode!==referral.value.trim().toUpperCase()&&!(await validateReferral()))return;const payload={firstName:form.first_name.value.trim(),lastName:form.last_name.value.trim(),email:form.email.value.trim(),phone:form.phone.value.trim(),loginCode:code.value.trim(),loginCodeConfirmation:confirmation.value.trim(),country:form.country.value,currency:form.currency.value,referralCode:referral.value.trim().toUpperCase()};const button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent="Creating account…";try{const response=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)}),data=await response.json();if(!response.ok){alertMessage(data.error||"Account could not be created.");fieldErrors(data.fields);button.disabled=false;button.textContent="Create Account";return}sessionStorage.setItem("vanguardprimeVerification",JSON.stringify({email:data.email,purpose:"registration",maskedEmail:data.maskedEmail}));location.replace("register-confirm.html")}catch(error){alertMessage(error.message||"Cannot reach the application server. Start it and try again.");button.disabled=false;button.textContent="Create Account"}};
})();
